// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZ1NFLc_XJjblEFpeqg0zDAxHeMAts_a8',
    appId: '1:692091775111:web:ed655f7f64724ea6b87022',
    messagingSenderId: '692091775111',
    projectId: 'fasum-app-2510f',
    authDomain: 'fasum-app-2510f.firebaseapp.com',
    storageBucket: 'fasum-app-2510f.firebasestorage.app',
    measurementId: 'G-G88F4TDBHE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnQtdVhH4qcAFRy-EiX1H1Ee7GqMDVShs',
    appId: '1:692091775111:android:8757708ddd5f577bb87022',
    messagingSenderId: '692091775111',
    projectId: 'fasum-app-2510f',
    storageBucket: 'fasum-app-2510f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZDlVQjQKJNwLSzekkS0Y9uU9F78n1c9o',
    appId: '1:692091775111:ios:e9537c65ad1277cbb87022',
    messagingSenderId: '692091775111',
    projectId: 'fasum-app-2510f',
    storageBucket: 'fasum-app-2510f.firebasestorage.app',
    iosBundleId: 'com.example.fasum',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZDlVQjQKJNwLSzekkS0Y9uU9F78n1c9o',
    appId: '1:692091775111:ios:e9537c65ad1277cbb87022',
    messagingSenderId: '692091775111',
    projectId: 'fasum-app-2510f',
    storageBucket: 'fasum-app-2510f.firebasestorage.app',
    iosBundleId: 'com.example.fasum',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZ1NFLc_XJjblEFpeqg0zDAxHeMAts_a8',
    appId: '1:692091775111:web:2449cf13dbc044aab87022',
    messagingSenderId: '692091775111',
    projectId: 'fasum-app-2510f',
    authDomain: 'fasum-app-2510f.firebaseapp.com',
    storageBucket: 'fasum-app-2510f.firebasestorage.app',
    measurementId: 'G-MW7MJ1364C',
  );
}
